package Screens;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import be.belgium.eid.eidlib.BeID;
import be.belgium.eid.exceptions.EIDException;
import deskundig.FileDes;
import java.awt.Cursor;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author Tycha
 */
public class Cryptography extends javax.swing.JFrame {

    private File inFile, outFile;
    private String key1Key;
    private String key2Key;

    /**
     * Creates new form Cryptography
     */
    public Cryptography() {
        inFile = null;
        outFile = null;
        key1Key = null;
        key2Key = null;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData = new javax.swing.JLabel();
        lblPassword3 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        lblPasswordTitle = new javax.swing.JLabel();
        lblFileChooser = new javax.swing.JLabel();
        txtFile2 = new javax.swing.JTextField();
        btnBrowse2 = new javax.swing.JButton();
        btnBrowse1 = new javax.swing.JButton();
        txtFile1 = new javax.swing.JTextField();
        lblFileChooser1 = new javax.swing.JLabel();
        BtnDoFileDes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chkDecrypt = new javax.swing.JCheckBox();
        btGetData = new javax.swing.JButton();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassword3 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        progBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblData.setText("No data found");

        lblPassword3.setText("Confirm password");

        lblPassword2.setText("Password");

        lblPasswordTitle.setText("Give 3 passwords ");

        lblFileChooser.setText("Select input file");

        txtFile2.setEditable(false);
        txtFile2.setForeground(new java.awt.Color(0, 102, 204));

        btnBrowse2.setText("Browse..");
        btnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse2ActionPerformed(evt);
            }
        });

        btnBrowse1.setText("Browse..");
        btnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse1ActionPerformed(evt);
            }
        });

        txtFile1.setEditable(false);
        txtFile1.setForeground(new java.awt.Color(0, 102, 204));
        txtFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFile1MouseEntered(evt);
            }
        });

        lblFileChooser1.setText("Select output file");

        BtnDoFileDes.setText("START");
        BtnDoFileDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoFileDesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        jLabel1.setText("3DES");

        chkDecrypt.setText("Decrypt");

        btGetData.setText("Get data");
        btGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetDataActionPerformed(evt);
            }
        });

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPasswordTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81)
                        .addComponent(chkDecrypt)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBrowse2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btGetData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword2)
                                    .addComponent(txtPassword3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDoFileDes, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(txtFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(progBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDecrypt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDoFileDes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFile1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFile1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFile1MouseEntered

    private void btnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse1ActionPerformed
        JFileChooser Kiezer = new JFileChooser("./");                       //zet standaard pad voor het bestand te kiezen dat ontcijfert moet worden
        Kiezer.setFileSelectionMode(JFileChooser.FILES_ONLY);    //men gaat hier de manier van kiezen koppelen aan de kiezer, dus zowel bestanden als mappen
        int Terugkeerwaarde = Kiezer.showOpenDialog(this);
        if (Terugkeerwaarde == JFileChooser.APPROVE_OPTION) {
            inFile = Kiezer.getSelectedFile();
            String inFilePath = Kiezer.getSelectedFile().toString();
            txtFile1.setText(inFilePath);
        }
    }//GEN-LAST:event_btnBrowse1ActionPerformed

    private void btnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse2ActionPerformed
        JFileChooser Kiezer = new JFileChooser("./");
        //zet standaard pad voor het bestand te kiezen dat ontcijfert moet worden
        Kiezer.setFileSelectionMode(JFileChooser.FILES_ONLY);    //men gaat hier de manier van kiezen koppelen aan de kiezer, dus zowel bestanden als mappen
        int Terugkeerwaarde = Kiezer.showSaveDialog(this);
        if (Terugkeerwaarde == JFileChooser.APPROVE_OPTION) {
            outFile = Kiezer.getSelectedFile();
            String outFilePath = Kiezer.getSelectedFile().toString();
            txtFile2.setText(outFilePath);
        }
    }//GEN-LAST:event_btnBrowse2ActionPerformed

    private void BtnDoFileDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoFileDesActionPerformed
        String soort = "";
        if (!txtPassword2.getText().equals(txtPassword3.getText())) {
            JOptionPane.showMessageDialog(null, "Passwords don't match!", "Error", JOptionPane.ERROR_MESSAGE);
            txtPassword2.setText("");
            txtPassword3.setText("");
        } else if (txtPassword2.getText().length() < 10) {
            JOptionPane.showMessageDialog(null, "Password needs to be at least 10 characters long", "Error", JOptionPane.ERROR_MESSAGE);
            txtPassword2.setText("");
            txtPassword3.setText("");
        } else if (inFile == null || outFile == null) {
            JOptionPane.showMessageDialog(null, "No 2 files selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (key1Key == null || key2Key == null) {
            JOptionPane.showMessageDialog(null, "No e-id data found (click Get data)", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] sleutels = {key1Key, key2Key, txtPassword3.getText()};
            Thread nThread;
            if (chkDecrypt.isSelected()) {
                soort = "\nDecrypt started";
                nThread = new Thread(new FileDes(sleutels, inFile, outFile, false, this));
            } else {
                soort = "\nEncrypt started";
                nThread = new Thread(new FileDes(sleutels, inFile, outFile, true, this));
            }
            nThread.start();
            txtOutput.append(soort);
            BtnDoFileDes.setEnabled(false);
            btGetData.setEnabled(false);
            btnBrowse1.setEnabled(false);
            btnBrowse2.setEnabled(false);
            txtPassword2.setEditable(false);
            txtPassword3.setEditable(false);

        }


    }//GEN-LAST:event_BtnDoFileDesActionPerformed

    private void btGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetDataActionPerformed
        txtOutput.setText("");
        setCursor(Cursor.WAIT_CURSOR);
        txtOutput.append("Reading E-id data");
        try {
            BeID id = new BeID(true);
            key1Key = id.getIDData().getCardNumber();
            key2Key = id.getIDData().getChipNumber();
            String name = id.getIDData().get1stFirstname() + " " + id.getIDData().getName();
            txtOutput.append("\nReading succesfull: " + name);
        } catch (EIDException ex) {
            txtOutput.append("\nReading failed: " + ex.getMessage());
        }
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btGetDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cryptography().setVisible(true);
            }
        });
    }

    public void desDone() {
        BtnDoFileDes.setEnabled(true);
        btGetData.setEnabled(true);
        btnBrowse1.setEnabled(true);
        btnBrowse2.setEnabled(true);
        txtPassword2.setEditable(true);
        txtPassword3.setEditable(true);
        progBar.setValue(0);
        txtOutput.append("\nDone");
    }

    public void setProgress(int pro) {
        progBar.setValue(pro);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDoFileDes;
    private javax.swing.JButton btGetData;
    private javax.swing.JButton btnBrowse1;
    private javax.swing.JButton btnBrowse2;
    private javax.swing.JCheckBox chkDecrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFileChooser;
    private javax.swing.JLabel lblFileChooser1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPassword3;
    private javax.swing.JLabel lblPasswordTitle;
    private javax.swing.JProgressBar progBar;
    private javax.swing.JTextField txtFile1;
    private javax.swing.JTextField txtFile2;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JPasswordField txtPassword3;
    // End of variables declaration//GEN-END:variables
}
